/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-05-09 09:34:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import il.ac.hit.samples.*;
import java.util.*;

public final class addCoupons_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=windows-1255");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("  <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.css\" />\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/mobile/1.4.2/jquery.mobile-1.4.2.min.js\"></script>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"themes/jqueysample.min.css\" />\r\n");
      out.write("<script type=\"text/javascript\">  \r\n");
      out.write("\r\n");
      out.write("  function checkform()\r\n");
      out.write("  {\r\n");
      out.write("\t  alert(\"Sdsdf\");\r\n");
      out.write("\t//var imageURL = document.addform.image.value; \r\n");
      out.write("\tvar price = document.addform.price.value;\r\n");
      out.write("\tvar okNum = /^[0-9]+$/;\t\r\n");
      out.write("\t//var okUrl= /^[0-9]+$/;\r\n");
      out.write("\t//var message=\"error: \\n\";\r\n");
      out.write("\tvar flag = true;\r\n");
      out.write("\r\n");
      out.write("\t\tif ((isEmpty(price)) == true ||(checkString(okNum, price)) == false)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t alert('you need to insert valid number');\r\n");
      out.write("\t\t\t document.addform.price.value = \"\";\r\n");
      out.write("\t\t\t flag = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\tif(flag == true)\r\n");
      out.write("    {\r\n");
      out.write("\t\talert(document.addform.date.value);\r\n");
      out.write("\t\talert(document.addform.details.value);\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t\twindow.location.reload();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function isEmpty(ob)\r\n");
      out.write("  {\r\n");
      out.write("  \tif(ob == null || ob == \"\")\r\n");
      out.write("  \t\t{\r\n");
      out.write("  \t\t\treturn true;\r\n");
      out.write("  \t\t}\r\n");
      out.write("  } \r\n");
      out.write("\r\n");
      out.write("  function checkString(checking,ob) \r\n");
      out.write("  {   \r\n");
      out.write("  \tif(ob.match(checking))  \r\n");
      out.write("  \t{  \r\n");
      out.write("  \t\treturn true;\r\n");
      out.write("  \t}  \r\n");
      out.write("  \telse  \r\n");
      out.write("  \t{  \r\n");
      out.write("  \t\treturn false;\r\n");
      out.write("  \t}  \r\n");
      out.write("  } \r\n");
      out.write("  \r\n");
      out.write(" </script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div data-role=\"page\" data-control-title=\"addCoupon\" id=\"page2\" >\r\n");
      out.write("    <div data-theme=\"a\" data-role=\"header\" >\r\n");
      out.write("        <h1>\r\n");
      out.write("            Header\r\n");
      out.write("        </h1>\r\n");
      out.write("        <a href=\"#page2\" class=\"ui-btn ui-btn-left\" data-direction=\"reverse\" data-rel=\"back\" >\r\n");
      out.write("            Button\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div role=\"main\" class=\"ui-content\" >\r\n");
      out.write("\r\n");
      out.write("        <form name=\"addform\" action=\"addCoupon\" method=\"POST\" onSubmit=\"return checkform();\"  >\r\n");
      out.write("          \r\n");
      out.write("            id:<input type=\"text\" name=\"id\" value=\"\" > \r\n");
      out.write("            coupon Name:<input type=\"text\" name=\"couponName\" value=\"\">\r\n");
      out.write("             <input type=\"hidden\" name=\"tza\" value=\"\">\r\n");
      out.write("           imageURL:<input type=\"text\" name=\"image\" value=\"\">\r\n");
      out.write("            Price:<input type=\"text\" name=\"price\" value=\"\">\r\n");
      out.write("          <label for=\"date\">Date Input:</label>\r\n");
      out.write("<input type=\"date\" name=\"date\" id=\"date\" value=\"\"  />\t\r\n");
      out.write("            <label for=\"time\">time Input:</label>\r\n");
      out.write("<input type=\"time\" name=\"time\" id=\"time\" value=\"\"  />\t\r\n");
      out.write("            Details: <textarea rows=\"4\" cols=\"50\" name=\"details\" value=\"\"></textarea>\r\n");
      out.write(" <select name=\"business\">\r\n");

@SuppressWarnings("unchecked")
ArrayList<Object> listBiz = (ArrayList<Object>)request.getAttribute("allBusiness");
	if(listBiz != null)
	{
		 
      out.write("\r\n");
      out.write("\t\t\t<option value=\"\" disabled selected>Select your Business</option>\r\n");
      out.write("\t\t");

		for(int i= 0;i<listBiz.size();i++)
		  {
      out.write("\r\n");
      out.write("\t\t\t");
 Business b = (Business)listBiz.get(i);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<option value=");
      out.print(b.getBuisnessId());
      out.write('>');
      out.print(b.getName());
      out.write("</option>\r\n");
      out.write("\t");
} 
		
		
	
	}
      out.write("\t\t\r\n");
      out.write("</select>\r\n");
      out.write(" <select name=\"categories\" >\r\n");
	
@SuppressWarnings("unchecked")
ArrayList<Object> listCat = (ArrayList<Object>)request.getAttribute("allCategories");
	if(listCat != null)
	{
		 
      out.write("\r\n");
      out.write("\t\t\t<option value=\"\" disabled selected>Select your Category</option>\r\n");
      out.write("\t\t");

		for(int i= 0;i<listCat.size();i++)
		  {
      out.write("\r\n");
      out.write("\t\t\t");
 Category cat = (Category)listCat.get(i);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<option>");
      out.print(cat.getCategoryName());
      out.write("</option>\r\n");
      out.write("\t");
} 
		
		
	
	}
      out.write("\t\t\r\n");
      out.write("</select>\r\n");
      out.write("             <input type=\"submit\"  id=\"btnsubmit\" data-icon=\"check\" data-iconpos=\"left\" value=\"Submit\" >\r\n");
      out.write("            \r\n");
      out.write("        </form>\r\n");
      out.write("   \r\n");
      out.write("     <div data-role=\"tabbar\" data-iconpos=\"top\" data-theme=\"a\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#businessAdmin\" data-transition=\"fade\" data-theme=\"\" data-icon=\"home\"\r\n");
      out.write("                class=\"ui-btn-active ui-state-persist\">\r\n");
      out.write("                    One\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\" data-transition=\"fade\" data-theme=\"\" data-icon=\"star\">\r\n");
      out.write("                    Two\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\" data-transition=\"fade\" data-theme=\"\" data-icon=\"info\">\r\n");
      out.write("                    Three\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
