/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-05-09 20:26:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import il.ac.hit.samples.*;
import java.util.List;
import java.util.ArrayList;

public final class coupon_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=windows-1255");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html> \r\n");
      out.write("<html> \r\n");
      out.write("<head> \r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("  <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n");
      out.write("\r\n");
      out.write("  <link href=\"https://s3.amazonaws.com/codiqa-cdn/codiqa.ext.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://s3.amazonaws.com/codiqa-cdn/mobile/1.4.0/jquery.mobile-1.4.0.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <script src=\"themes/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("  <script src=\"https://s3.amazonaws.com/codiqa-cdn/mobile/1.4.0/jquery.mobile-1.4.0.min.js\"></script>\r\n");
      out.write("  <script src=\"https://s3.amazonaws.com/codiqa-cdn/codiqa.ext.js\"></script>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"themes/jqueysample.min.css\" />\r\n");
      out.write("\r\n");
      out.write("</head> \r\n");
      out.write("<body> \r\n");
 
	if(application.getAttribute("coupoHibernate")==null)
	{
		application.setAttribute("coupoHibernate",CuponHibernate.getCouponsHibernate());
	}

      out.write('\r');
      out.write('\n');
      out.write(' ');
 Coupon ob = (Coupon)request.getAttribute("timestamp");
      out.write("\r\n");
      out.write("<div id=\"restau\" data-role=\"page\" data-add-back-btn=\"true\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div data-role=\"header\"> \r\n");
      out.write("\t\t<h1>Coupon page</h1>\r\n");
      out.write("\t\t        <a href=\"/CouponServlet/contact\" class=\"ui-btn ui-btn-left\">\r\n");
      out.write("            Previous</a>\r\n");
      out.write("\t</div> \r\n");
      out.write("\t\r\n");
      out.write("\t<div data-role=\"content\">\r\n");
      out.write("\t<div class=\"ui-grid-a\" id=\"restau_infos\">\t\r\n");
      out.write("\t<p><img src=\"");
      out.print( ob.getimage() );
      out.write("\" alt=\"picture\" width=\"240px\" height=\"180px\"/></p>\r\n");
      out.write("\t\t<div class=\"ui-block-a\">\r\n");
      out.write("\t\t<h1>");
      out.print( ob.getCouponName() );
      out.write("</h1>\r\n");
      out.write("\t\t<p><strong>");
      out.print(ob.getdetail() );
      out.write(" </strong></p><br>\t\t\t\r\n");
      out.write("\t\t\t\t<hr/>\r\n");
      out.write("\t\t<p><strong>Price: ");
      out.print( ob.getPrice());
      out.write("</strong></p>\r\n");
      out.write("\t\t <hr/>\r\n");
      out.write("\t\t<p><strong>Expire Date:<br>");
      out.print( ob.getLastDate());
      out.write("</strong></p>\r\n");
      out.write("\t    \r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\r\n");
      out.write("\t</div><!-- /grid-a -->\r\n");
      out.write("\t<hr/>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"ui-grid-a\" id=\"contact_infos\">\t\r\n");
      out.write("\t\t<div class=\"ui-block-a\">\r\n");
      out.write("\t\t<h2> Contact us : ");
      out.print(ob.getBusiness().getName() );
      out.write("</h2>\r\n");
      out.write("\t\t<p><b>Adress</b> :  ");
      out.print(ob.getBusiness().getAdress() );
      out.write("</p>\r\n");
      out.write("\t\t<p>Phone :  ");
      out.print(ob.getBusiness().getPhone() );
      out.write("</p>\t\t\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t<div class=\"ui-block-b\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<img src=\"http://icons.iconarchive.com/icons/wwalczyszyn/android-style-honeycomb/128/Phone-icon.png\" alt=\"plan jeanette\"/>\r\n");
      out.write("\t</div><!-- /grid-a -->\r\n");
      out.write("\t<div id=\"contact_buttons\">\t\r\n");
      out.write("\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CouponServlet/ShoppingCart/");
      out.print(String.valueOf(ob.getId()));
      out.write("\" data-role=\"button\" data-icon=\"star\">Add To Favorites</a>\r\n");
      out.write("\t<a href=\"\"  data-role=\"button\" data-icon=\"star\">Share on Facebook</a>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t<hr/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!-- /page -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
