/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-05-10 21:19:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import il.ac.hit.samples.*;
import java.util.*;

public final class couponByCategories_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=windows-1255");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("  <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n");
      out.write("\r\n");
      out.write("  <link href=\"https://s3.amazonaws.com/codiqa-cdn/codiqa.ext.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://s3.amazonaws.com/codiqa-cdn/mobile/1.4.0/jquery.mobile-1.4.0.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <script src=\"themes/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("  <script src=\"https://s3.amazonaws.com/codiqa-cdn/mobile/1.4.0/jquery.mobile-1.4.0.min.js\"></script>\r\n");
      out.write("  <script src=\"https://s3.amazonaws.com/codiqa-cdn/codiqa.ext.js\"></script>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"themes/jqueysample.min.css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div data-role=\"page\" data-control-title=\"addCoupon\" id=\"page2\">\r\n");
      out.write("    <div data-theme=\"a\" data-role=\"header\">\r\n");
      out.write("        <h1>\r\n");
      out.write("            All Coupon\r\n");
      out.write("        </h1>\r\n");
      out.write("        <a href=\"#page2\" class=\"ui-btn ui-btn-left\" data-direction=\"reverse\" data-rel=\"back\">\r\n");
      out.write("            Previous</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div role=\"main\" class=\"ui-content\">\r\n");
      out.write("  \r\n");
      out.write("<ul data-role=\"listview\" data-inset=\"true\" >\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");

 @SuppressWarnings("unchecked")
 ArrayList<Coupon> listCoupon = (ArrayList<Coupon>)request.getAttribute("allCouponsByCategories");
	try
	{
		if (listCoupon != null && !listCoupon.isEmpty())
		{
			for(int i=0;i<listCoupon.size();i++)
			{
      out.write("\r\n");
      out.write("\t\t\t");
 Coupon coupon = (Coupon)listCoupon.get(i);
      out.write("\r\n");
      out.write("   \t   \t  <li><a href=\"coupon/");
      out.print(String.valueOf(coupon.getId()));
      out.write("\" data-transition=\"slidedown\"><img src=\"");
      out.print(coupon.getimage());
      out.write("\" width=\"200px\" height=\"200px\"/><h3>");
      out.print(coupon.getCouponName());
      out.write("</h3></a></li>\r\n");
      out.write("\t  ");
}
 }
	}
	catch(NullPointerException e)
	{
		throw new CouponExceptionPlatrform("Coupon list is Null", e);     
	}
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</ul>\r\n");
      out.write("</div>\r\n");
      out.write("    <div data-role=\"tabbar\" data-iconpos=\"top\" data-theme=\"a\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#page2\" data-transition=\"fade\" data-theme=\"\" data-icon=\"home\"\r\n");
      out.write("                class=\"ui-btn-active ui-state-persist\">\r\n");
      out.write("                    One\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\" data-transition=\"fade\" data-theme=\"\" data-icon=\"star\">\r\n");
      out.write("                    Two\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\" data-transition=\"fade\" data-theme=\"\" data-icon=\"info\">\r\n");
      out.write("                    Three\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
