/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-05-10 21:33:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=windows-1255");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <title></title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("  <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">\r\n");
      out.write("\r\n");
      out.write("  <link href=\"https://s3.amazonaws.com/codiqa-cdn/codiqa.ext.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"https://s3.amazonaws.com/codiqa-cdn/mobile/1.4.0/jquery.mobile-1.4.0.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://s3.amazonaws.com/codiqa-cdn/mobile/1.4.0/jquery.mobile-1.4.0.min.js\"></script>\r\n");
      out.write("  <script src=\"https://s3.amazonaws.com/codiqa-cdn/codiqa.ext.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Theme CSS -->\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"homeTheme/jqueysample.min.css\" />\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div data-role=\"page\" data-control-title=\"homepage\" id=\"homePage\" data-ajax=\"false\">\r\n");
      out.write("    <div data-theme=\"a\" data-role=\"header\">\r\n");
      out.write("        <h3 class=\"ui-title\">\r\n");
      out.write("            Copons\r\n");
      out.write("        </h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div role=\"main\" class=\"ui-content\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <table align=\"center\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("<a href=\"CouponServlet/beforeAdd\" data-role=\"button\" data-theme=\"g\" >admin</a>\r\n");
      out.write("</td>\r\n");
      out.write("<td>\r\n");
      out.write("\r\n");
      out.write("<a href=\"CouponServlet/contact\" data-role=\"button\" data-theme=\"b\">coupon</a>\r\n");
      out.write(" </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" <tr>\r\n");
      out.write("<td>\r\n");
      out.write(" <a href=\"#\" data-role=\"button\" data-theme=\"c\" data-ajax=\"false\">help</a>\r\n");
      out.write(" </td>\r\n");
      out.write(" <td>\r\n");
      out.write(" <a href=\"#\" data-role=\"button\" data-theme=\"f\" data-ajax=\"false\">about</a>\r\n");
      out.write(" </td>\r\n");
      out.write(" </tr>\r\n");
      out.write(" </tr>\r\n");
      out.write("  <td>\r\n");
      out.write(" <a href=\"CouponServlet/categories\" data-role=\"button\" data-theme=\"f\" >about</a>\r\n");
      out.write(" </td>\r\n");
      out.write(" \r\n");
      out.write(" </tr>\r\n");
      out.write("\r\n");
      out.write(" </table>\r\n");
      out.write("    <div data-role=\"tabbar\" data-iconpos=\"top\" data-theme=\"a\" data-ajax=\"false\"> \r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"home.jsp\" data-transition=\"flip\" data-theme=\"\" data-icon=\"home\">\r\n");
      out.write("                    Home\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/shoppingcart.jsp\" data-transition=\"slideup\" data-theme=\"\" data-icon=\"star\">\r\n");
      out.write("                    My Coupons\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"contact.jsp\" data-transition=\"flip\" data-theme=\"\" data-icon=\"info\">\r\n");
      out.write("                    Contact As\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
