/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-05-10 15:03:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class location_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=windows-1255");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://jqueryjs.googlecode.com/files/jquery-1.3.2.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("/*var myLocation; // global variable to store lat/lng\r\n");
      out.write("if (navigator && navigator.geolocation) {\r\n");
      out.write("  // HTML5 GeoLocation\r\n");
      out.write("  function getLocation(position) {\r\n");
      out.write("    myLocation = {\r\n");
      out.write("      \"lat\": position.coords.latitude, \r\n");
      out.write("      \"lng\": position.coords.longitude\r\n");
      out.write("      \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    alert(position.coords.latitude);\r\n");
      out.write("  }\r\n");
      out.write("  navigator.geolocation.getCurrentPosition(getLocation);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}*/\r\n");
      out.write("alert(\"fgf\");\r\n");
      out.write("navigator.geolocation.getCurrentPosition(function(pos){\r\n");
      out.write("\t alert(\"fgf2\");\r\n");
      out.write("    var userPosition = pos;\r\n");
      out.write("    var longitude = userPosition.coords.longitude;\r\n");
      out.write("    var latitude = userPosition.coords.latitude;\r\n");
      out.write("    alert(longitude + \" \" +latitude);\r\n");
      out.write(" \r\n");
      out.write("     $.ajax({\r\n");
      out.write("        url: 'http://localhost:8080/bdika/CouponServlet/location',\r\n");
      out.write("        type: 'POST',\r\n");
      out.write("        \tdata: {\r\n");
      out.write("        \t\tlongitude: longitude,\r\n");
      out.write("        \t\tlatitude : latitude\r\n");
      out.write("            },\r\n");
      out.write("    });\r\n");
      out.write(" \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1255\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
