/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-05-10 17:47:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.couponAdmin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.lang.*;

public final class businessManagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=windows-1255");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("       <head>   \r\n");
      out.write("           \t");

            // checking if username seesion is open, it redirect to login 
  		if(session.getAttribute("username") == null)
  		{
  			RequestDispatcher dispatcher = request.getRequestDispatcher("/CouponServlet/admin");	
			dispatcher.forward(request, response);
  		}

  		
      out.write("\r\n");
      out.write("              <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("              <title>Business Management - Couponic Admin</title>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("              <!-- Bootstrap core CSS -->\r\n");
      out.write("              <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("              <!--custom CSS-->\r\n");
      out.write("              <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/css/sb-admin.css\" rel=\"stylesheet\">\r\n");
      out.write("              <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("              <!-- Page Specific CSS -->\r\n");
      out.write("              <link rel=\"stylesheet\" href=\"http://cdn.oesmith.co.uk/morris-0.4.3.min.css\">\r\n");
      out.write("          </head>\r\n");
      out.write("\r\n");
      out.write("          <body>\r\n");
      out.write("\r\n");
      out.write("          <div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("              <!-- Sidebar -->\r\n");
      out.write("              <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("                  <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("                  <div class=\"navbar-header\">\r\n");
      out.write("                      <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/couponAdmin.jsp\">Admin-Couponic</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("        <div class=\"collapse navbar-collapse navbar-ex1-collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav side-nav\">\r\n");
      out.write("            <li class=\"active\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/couponAdmin.jsp\"><i class=\"fa fa-dashboard\"></i>Dashboard</a></li>           \r\n");
      out.write("           <li class=\"dropdown\">\r\n");
      out.write("              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/couponManagement.jsp\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"fa fa-book fa-fw\"></i> Coupon Management <b class=\"caret\"></b></a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CouponServlet/addCouponInit\"><i class=\"fa fa-plus\"></i> Add Coupon</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/deleteCoupon.jsp\"><i class=\"fa fa-trash-o\"></i> Delete Coupon</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CouponServlet/updateCouponInit\"><i class=\"fa fa-pencil\"></i> Update Coupon</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("\t\t\t <li class=\"dropdown\">\r\n");
      out.write("              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/businessManagement.jsp\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"fa fa-th\"></i> Business Management <b class=\"caret\"></b></a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/addBusiness.jsp\"><i class=\"fa fa-plus\"></i> Add Business</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/deleteBusiness.jsp\"><i class=\"fa fa-trash-o\"></i> Delete Business</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/updateBusiness.jsp\"><i class=\"fa fa-pencil \"></i> Update Business</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("\t\t\t <li class=\"dropdown\">\r\n");
      out.write("              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/categoryManagement.jsp\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"fa fa-caret-square-o-down\"></i> Categories Management <b class=\"caret\"></b></a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/addCategory.jsp\"><i class=\"fa fa-plus\"></i> Add Category</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/deleteCategory.jsp\"><i class=\"fa fa-trash-o\"></i> Delete Category</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/updateCategory.jsp\"><i class=\"fa fa-pencil \"></i> Update Category</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\r\n");
      out.write("    <ul class=\"nav navbar-nav navbar-right navbar-user\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <li class=\"dropdown user-dropdown\">\r\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"fa fa-user\"></i>admin<b class=\"caret\"></b></a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">            \r\n");
      out.write("                <li class=\"divider\"></li>\r\n");
      out.write("                 <form role=\"form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CouponServlet/logout\" method=\"POST\" onSubmit=\"return check();\">\r\n");
      out.write("                   <input type=\"hidden\" name=\"logout\" value=\"logout\" > \r\n");
      out.write("                <li><i class=\"fa fa-power-off\"></i> <button type=\"submit\"  class=\"btn btn-default\" >Logout</button></li>\r\n");
      out.write("                </form>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div><!-- /.navbar-collapse -->\r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write("      <div id=\"page-wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-12\">\r\n");
      out.write("            <h1>Business Management <small>Couponic Admin Panel</small></h1>\r\n");
      out.write("            <ol class=\"breadcrumb\">\r\n");
      out.write("              <li class=\"active\"><i class=\"fa fa-dashboard\"></i> Dashboard</li>\r\n");
      out.write("            </ol>\r\n");
      out.write("            <div class=\"alert alert-success alert-dismissable\">\r\n");
      out.write("              Welcome to Couponic Admin by <a class=\"alert-link\" href=\"\">Inna  and Tzahi </a></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div><!-- /.row -->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-3\">\r\n");
      out.write("            <div class=\"panel panel-info\">\r\n");
      out.write("              <div class=\"panel-heading\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-xs-6\">\r\n");
      out.write("                    <i class=\"fa fa-plus fa-5x\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-xs-6 text-right\">\r\n");
      out.write("                    <p class=\"announcement-heading\">1</p>\r\n");
      out.write("                    <p class=\"announcement-text\">Couponic</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("                <div class=\"panel-footer announcement-bottom\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xs-6\">\r\n");
      out.write("                     <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/addBusiness.jsp\">Add New Business</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xs-6 text-right\">\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/addBusiness.jsp\"\"><i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                          \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-3\">\r\n");
      out.write("            <div class=\"panel panel-warning\">\r\n");
      out.write("              <div class=\"panel-heading\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-xs-6\">\r\n");
      out.write("                    <i class=\"fa fa-trash-o fa-5x\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-xs-6 text-right\">\r\n");
      out.write("                    <p class=\"announcement-heading\">2</p>\r\n");
      out.write("                    <p class=\"announcement-text\">Couponic</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"panel-footer announcement-bottom\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xs-6\">\r\n");
      out.write("                     <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/deleteBusiness.jsp\">Delete Business</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xs-6 text-right\">\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/deleteBusiness.jsp\"><i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-lg-3\">\r\n");
      out.write("            <div class=\"panel panel-danger\">\r\n");
      out.write("              <div class=\"panel-heading\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-xs-6\">\r\n");
      out.write("                    <i class=\"fa fa-pencil fa-5x\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-xs-6 text-right\">\r\n");
      out.write("                    <p class=\"announcement-heading\">3</p>\r\n");
      out.write("                    <p class=\"announcement-text\">Couponic</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("                 <div class=\"panel-footer announcement-bottom\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xs-6\">\r\n");
      out.write("                     <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CouponServlet/updateCouponInit\">Business Update</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xs-6 text-right\">\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/CouponServlet/updateCouponInit\"><i class=\"fa fa-arrow-circle-right\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div><!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/js/jquery-1.10.2.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page Specific Plugins -->\r\n");
      out.write("    <script src=\"http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js\"></script>\r\n");
      out.write("    <script src=\"http://cdn.oesmith.co.uk/morris-0.4.3.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/couponAdmin/js/morris/chart-data-morris.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
